### ISSUE TITLE
How can I add a checkbox element on my paperbits app?

### ISSUE THREAD

**Issue by chang-nicolas** [paperbits/paperbits-forms#3]
Hi, developers!!!
I wanna add a checkbox input on my paperbits app which already exists.
But couldn't find that element.
Is there someone who can teach me how to add the checkbox on my app?
Thank you.

**Comment by azaslonov** [comment]
Hi @chang-nicolas,

The checkbox can be added only on a Form widget. So, you add Form first, then you'll see all the form controls in Add widget dialog.

Hope that helps.

**Comment by chang-nicolas** [comment]
Thank you for your answer, @azaslonov 
But still, I have an issue.
If the state of the checkbox changes in this case it changes from true to false, I need to replace a message on the main page.
Those are from different components and not related to each other.
They are absolutely individual.
How can I implement that?
The template(Html content) of the main page component should be updated as soon as the value of the checkbox component changes.
Hopefully, that makes sense.
Thank you.

**Comment by azaslonov** [comment]
This seems like very custom behavior that can't be configured visually. In this case, the only option I can suggest is to implement your own form widget that would take it all into account. For example, you can take a look at something like this [here](https://github.com/Azure/api-management-developer-portal/tree/master/src/components/users/signin/ko/runtime).
