### ISSUE TITLE
Setting custom action and method for forms

### ISSUE THREAD

**Issue by msrshahrukh100** [paperbits/paperbits-forms#4]
This is not actually an issue but a question.
How can we set custom actions and methods for the forms module? In the documentation, I don't see any examples of this.
Also,
1. Is there any forum where we can discuss queries on Paperbits rather than posting here under issues?
2. Does Paperbits require us to buy any license? Currently, I don't see any such information present on the main website. Is the software free to use and develop commercial applications?

**Comment by azaslonov** [comment]
Hi @msrshahrukh100,

1. The form widget editor has fields for the method and URL:
   <img width="257" alt="image" src="https://user-images.githubusercontent.com/2320302/204896898-b8544cd2-e09f-4044-b003-1643f001192b.png">

    But I assume you're asking about some other custom logic? Could you please provide more context on what you'd like to achieve?

2. We don't require to buy licenses for currently available modules, but we offer paid support, shall you need it. For details please shoot us email to support@paperbits.io.

**Comment by msrshahrukh100** [comment]
ok got it, thanks! I needed this exact thing.
On the default form that gets inserted it was a bit hard to figure out how to edit the submit URL. But clicking on the outer edge opened the above widget for editing the submit URL.
